# Only for docker-compose
# Do not use Docker Swarm !
version: "2"
services:
  allinone:
    pid: host
    image: neuvector/allinone
    privileged: true
    environment:
    - CLUSTER_JOIN_ADDR=<IP>
    ports:
    - 18300:18300
    - 18301:18301
    - 18400:18400
    - 18401:18401
    - 18301:18301/udp
    - 8443:8443
    - 10443:10443
    volumes:
    - /lib/modules:/lib/modules
    - /var/neuvector:/var/neuvector
    - /var/run/docker.sock:/var/run/docker.sock
    - /proc:/host/proc:ro
    - /sys/fs/cgroup:/host/cgroup:ro

# docker-compose -f docker-compose.neuvector.yaml up -d
