version: "3.1"

services:

  redis:
    image: redis:3.0.7-alpine
    environment:
      - TZ=${TZ}
    networks:
      - front-tier
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - TZ=${TZ}
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
    deploy:
      placement:
        constraints: [node.role == manager]

  vote:
    image: "vertxswarm/verticle-vote:latest"
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ}
    depends_on:
      - redis
    networks:
      - front-tier
    deploy:
      placement:
        constraints: [node.role != manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

  result:
    image: "vertxswarm/verticle-result:latest"
    ports:
      - 8081:8081
    environment:
      - TZ=${TZ}
    depends_on:
      - postgres
    networks:
      - back-tier
    deploy:
      placement:
        constraints: [node.role != manager]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

  worker:
    image: "vertxswarm/verticle-worker:latest"
    environment:
      - TZ=${TZ}
    depends_on:
      - postgres
      - redis
    networks:
      - front-tier
      - back-tier
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - 5000:8080
    stop_grace_period: 5s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  # docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer --no-auth
  #portainer:
  #  image: portainer/portainer
  #  ports:
  #    - 9000:9000
  #  volumes:
  #    - "/var/run/docker.sock:/var/run/docker.sock"
  #    - "portainer-data:/data"
  #  command: --no-auth
  #  deploy:
  #    placement:
  #      constraints: [node.role == manager]

volumes:
  db-data:
  portainer-data:

networks:
  front-tier:
  back-tier:

