version: "3"

services:

  redis:
    image: redis:3.0.7-alpine
    environment:
      - TZ=${TZ}
    ports: ["6379:6379"]

  postgres:
    image: postgres:9.6
    ports: ["5432:5432"]
    environment:
      - POSTGRES_USER=postgres
      - TZ=${TZ}
    volumes:
      - "db-data:/var/lib/postgresql/data"

  vote:
    image: "vertx-dockerswarm/verticle-vote:${TAG_VOTE}"
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ}
    depends_on:
      - redis

  result:
      image: "vertx-dockerswarm/verticle-result:${TAG_RESULT}"
      ports:
        - 8081:8081
      environment:
        - TZ=${TZ}
      depends_on:
        - postgres

  worker:
      image: "vertx-dockerswarm/verticle-worker:${TAG_WORKER}"
      environment:
        - TZ=${TZ}
      depends_on:
        - postgres
        - redis

volumes:
  db-data:

# networks:
  #front-tier:
  #back-tier:


