version: "3"

services:

  vds-redis:
    image: redis:3.0.7-alpine
    environment:
      - TZ=${TZ}
    networks:
      - front-tier
    deploy:
      placement:
        constraints: [node.role == manager]

  vds-postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - TZ=${TZ}
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
    deploy:
      placement:
        constraints: [node.role == manager]

  vds-vote:
    image: "vertx-swarm/verticle-vote:latest"
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ}
    depends_on:
      - vds-redis
    networks:
      - front-tier

  vds-result:
    image: "vertx-swarm/verticle-result:latest"
    ports:
      - 8081:8081
    environment:
      - TZ=${TZ}
    depends_on:
      - vds-postgres
    networks:
      - back-tier

  vds-worker:
    image: "vertx-swarm/verticle-worker:latest"
    environment:
      - TZ=${TZ}
    depends_on:
      - vds-postgres
      - vds-redis
    networks:
      - front-tier
      - back-tier
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  db-data:

networks:
  front-tier:
  back-tier:

