version: "3"

services:

  redis:
    image: redis:3.0.7-alpine
    container_name: vds-redis
    environment:
      - TZ=${TZ}
    ports: ["6379:6379"]

  vote:
    image: "vertx-dockerswarm/verticle-vote:${TAG_VOTE}"
    container_name: vds-vote
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ}
    depends_on:
      - redis

volumes:
  db-data:

# networks:
  #front-tier:
  #back-tier:


