version: "3"

services:

  redis:
    image: redis:3.0.7-alpine
    container_name: vds-redis
    environment:
      - TZ=${TZ}
    ports: ["6379:6379"]
    networks:
      - front-tier

  postgres:
    image: postgres:9.6-alpine
    container_name: vds-postgres
    ports: ["5432:5432"]
    environment:
      - POSTGRES_USER=postgres
      - TZ=${TZ}
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  vote:
    image: "vertxswarm/verticle-vote:${TAG_VOTE}"
    container_name: vds-vote
    ports:
      - 8080:8080
    environment:
      - TZ=${TZ}
    depends_on:
      - redis
    networks:
      - front-tier

  result:
    image: "vertxswarm/verticle-result:${TAG_RESULT}"
    container_name: vds-result
    ports:
      - 8081:8081
    environment:
      - TZ=${TZ}
    depends_on:
      - postgres
    networks:
      - back-tier

  worker:
    image: "vertxswarm/verticle-worker:${TAG_WORKER}"
    container_name: vds-worker
    environment:
      - TZ=${TZ}
    depends_on:
      - postgres
      - redis
    networks:
      - front-tier
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:


