version: "3"

services:

  redis:
    image: redis:3.0.7-alpine
    container_name: redis
    ports: ["6379:6379"]

  postgres:
    image: postgres:9.6
    container_name: postgres
    ports: ["5342:5342"]

  vote:
    image: vertx-dockerswarm/verticle-vote:latest
    container_name: vote



