version: "3"

services:

  redis:
    image: redis:3.0.7-alpine
    container_name: vds-redis
    environment:
      - TZ=${TZ}
    ports: ["6379:6379"]

  postgres:
    image: postgres:9.6
    container_name: vds-postgres
    ports: ["5342:5342"]
    environment:
      - POSTGRES_USER=postgres
      - TZ=${TZ}
    volumes:
      - "db-data:/var/lib/postgresql/data"

  vote:
    image: vertx-dockerswarm/verticle-vote:${TAG_VOTE:latest}
    container_name: vote
    environment:
      - TZ=${TZ}
    depends_on:
      - redis

  result:
      image: vertx-dockerswarm/verticle-worker:${TAG_RESULT:latest}
      container_name: vote
      environment:
        - TZ=${TZ}
      depends_on:
        - postgres

  worker:
      image: vertx-dockerswarm/verticle-worker:${TAG_WORKER:latest}
      container_name: vote
      environment:
        - TZ=${TZ}
      depends_on:
        - postgres
        - redis

volumes:
  db-data:

# networks:
  #front-tier:
  #back-tier:


